import { useEffect, useMemo, useState } from "react";
import { Activity, Bot, Cable, CheckCircle2, GitBranch, History, Network, Play, RefreshCw, Search, Settings2, ShieldAlert, Sparkles, TrendingUp, X, Zap } from "lucide-react";

const API = import.meta.env.VITE_API_URL || "http://localhost:5000";
const tabs = [
  ["noc", "NOC", Activity],
  ["topology", "Topology", Network],
  ["correlation", "Correlation", GitBranch],
  ["rca", "Root Cause", ShieldAlert],
  ["health", "Interface Health", Cable],
  ["analytics", "Analytics", TrendingUp],
  ["changes", "Config Changes", History],
  ["automation", "Automation", Play],
  ["assistant", "AI Assistant", Bot]
];

function Card({ children, className = "" }) { return <section className={`rounded-2xl border border-slate-800/80 bg-slate-900/70 shadow-2xl shadow-black/10 ${className}`}>{children}</section>; }
function Badge({ children, tone = "blue" }) { const c = { blue: "border-blue-500/20 bg-blue-500/10 text-blue-300", green: "border-emerald-500/20 bg-emerald-500/10 text-emerald-300", amber: "border-amber-500/20 bg-amber-500/10 text-amber-300", red: "border-red-500/20 bg-red-500/10 text-red-300" }; return <span className={`rounded-full border px-2 py-1 text-[10px] font-bold uppercase tracking-wider ${c[tone]}`}>{children}</span>; }
function Metric({ label, value, tone = "blue" }) { return <div className="rounded-xl border border-slate-800 bg-slate-950/60 p-4"><p className="text-[10px] uppercase tracking-[.18em] text-slate-600">{label}</p><p className={`mt-2 text-2xl font-bold ${tone === "red" ? "text-red-300" : tone === "green" ? "text-emerald-300" : tone === "amber" ? "text-amber-300" : "text-white"}`}>{value}</p></div>; }

async function request(path, options = {}) { const response = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json" }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || `Request failed (${response.status})`); return data; }

export default function Phase4OperationsCenter() {
  const [open, setOpen] = useState(false), [tab, setTab] = useState("noc"), [overview, setOverview] = useState(null), [analytics, setAnalytics] = useState(null), [correlation, setCorrelation] = useState(null), [rca, setRca] = useState(null), [changes, setChanges] = useState(null), [assistant, setAssistant] = useState(null), [question, setQuestion] = useState("What should I investigate first?"), [busy, setBusy] = useState(""), [message, setMessage] = useState("");

  const loadOverview = async () => setOverview(await request("/api/phase4/overview"));
  useEffect(() => { if (open) loadOverview().catch(e => setMessage(e.message)); }, [open]);

  const run = async (key, fn) => { setBusy(key); setMessage(""); try { await fn(); setMessage("Completed successfully."); } catch (e) { setMessage(e.message); } finally { setBusy(""); } };
  const openTab = key => { setTab(key); if (key === "analytics") run("analytics", async () => setAnalytics(await request("/api/phase4/analytics?hours=24"))); if (key === "correlation") run("correlation", async () => setCorrelation(await request("/api/incidents/correlation"))); if (key === "rca") run("rca", async () => setRca(await request("/api/phase4/rca"))); if (key === "changes") run("changes", async () => setChanges(await request("/api/phase4/config-changes"))); };
  const k = overview?.kpis || {};
  const active = useMemo(() => (overview?.recentIncidents || []).filter(i => i.status !== "RESOLVED"), [overview]);

  async function automation(action) { await request("/api/phase4/automation/run", { method: "POST", body: JSON.stringify({ action }) }); await loadOverview(); }
  async function ask() { setBusy("assistant"); try { setAssistant(await request("/api/phase4/assistant", { method: "POST", body: JSON.stringify({ question }) })); } catch (e) { setMessage(e.message); } finally { setBusy(""); } }

  return <>
    <button onClick={() => setOpen(true)} className="fixed bottom-5 right-5 z-50 inline-flex items-center gap-2 rounded-2xl border border-blue-400/20 bg-blue-600 px-4 py-3 text-xs font-bold text-white shadow-2xl shadow-blue-950/40 transition hover:-translate-y-0.5 hover:bg-blue-500"><Sparkles size={15}/> Phase 4 Command Center</button>
    {open && <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/75 p-3 backdrop-blur-sm sm:p-6">
      <div className="flex h-[min(94vh,900px)] w-full max-w-[1500px] flex-col overflow-hidden rounded-3xl border border-slate-700/80 bg-[#060b14] shadow-2xl">
        <header className="flex shrink-0 items-center justify-between border-b border-slate-800/80 bg-slate-950/90 px-5 py-4"><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-600/15 p-2 text-blue-300"><Zap size={18}/></div><div><h2 className="font-semibold text-white">Phase 4 Operations Suite</h2><p className="text-[10px] uppercase tracking-[.2em] text-slate-600">Network intelligence · performance · automation</p></div></div><div className="flex items-center gap-2"><button title="Refresh overview" onClick={() => run("refresh", loadOverview)} className="rounded-xl border border-slate-800 p-2 text-slate-400 hover:bg-slate-800 hover:text-white"><RefreshCw size={16} className={busy === "refresh" ? "animate-spin" : ""}/></button><button onClick={() => setOpen(false)} className="rounded-xl border border-slate-800 p-2 text-slate-400 hover:bg-slate-800 hover:text-white"><X size={17}/></button></div></header>
        <div className="flex min-h-0 flex-1">
          <nav className="hidden w-56 shrink-0 overflow-y-auto border-r border-slate-800/80 bg-slate-950/50 p-3 md:block">{tabs.map(([id, label, Icon]) => <button key={id} onClick={() => openTab(id)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-xs font-semibold transition ${tab === id ? "bg-blue-500/10 text-blue-300 ring-1 ring-blue-500/20" : "text-slate-500 hover:bg-slate-800/50 hover:text-slate-200"}`}><Icon size={15}/>{label}</button>)}<div className="mt-5 rounded-xl border border-emerald-500/10 bg-emerald-500/5 p-3 text-[10px] leading-5 text-slate-500"><span className="font-bold text-emerald-300">SAFE AUTOMATION</span><br/>Actions here are read-only discovery, correlation and snapshot workflows. No device configuration is pushed automatically.</div></nav>
          <main className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-6">
            <div className="mb-4 flex gap-2 overflow-x-auto pb-1 md:hidden">{tabs.map(([id, label, Icon]) => <button key={id} onClick={() => openTab(id)} className={`flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-[11px] font-semibold ${tab === id ? "bg-blue-600 text-white" : "bg-slate-900 text-slate-500"}`}><Icon size={13}/>{label}</button>)}</div>
            {message && <div className="mb-4 flex items-center justify-between rounded-xl border border-blue-500/20 bg-blue-500/5 px-4 py-3 text-xs text-blue-200"><span>{message}</span><button onClick={() => setMessage("")}><X size={13}/></button></div>}
            {tab === "noc" && <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active incidents" value={k.activeIncidents ?? "—"} tone={k.activeIncidents ? "amber" : "green"}/><Metric label="Down devices" value={k.downDevices ?? "—"} tone="red"/><Metric label="Degraded devices" value={k.degradedDevices ?? "—"} tone="amber"/><Metric label="Peak utilization" value={`${Number(k.peakUtilization || 0).toFixed(1)}%`}/></div><Card><div className="border-b border-slate-800/80 p-5"><h3 className="font-semibold text-white">NOC attention queue</h3><p className="mt-1 text-xs text-slate-600">Sorted by operational urgency</p></div><div className="divide-y divide-slate-800/60">{active.length ? active.map(i => <div key={i.incidentId} className="flex flex-wrap items-center gap-3 p-4"><span className="font-mono text-xs text-white">{i.incidentId}</span><Badge tone={i.severity === "critical" ? "red" : i.severity === "high" ? "amber" : "blue"}>{i.severity}</Badge><span className="min-w-[150px] flex-1 text-sm text-slate-300">{i.device}</span><span className="text-xs text-slate-500">{i.status}</span></div>) : <div className="p-10 text-center text-sm text-slate-500">No active incidents in the recent window.</div>}</div></Card></div>}
            {tab === "topology" && <div className="space-y-5"><Card className="p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><Badge tone="green">4.1 Critical</Badge><h3 className="mt-3 text-xl font-semibold text-white">Topology discovery</h3><p className="mt-2 max-w-2xl text-sm text-slate-500">Refresh CDP/LLDP infrastructure relationships without blocking the normal dashboard. Use the existing interactive topology canvas for visual drill-down.</p></div><button onClick={() => run("topology", () => automation("topology"))} disabled={!!busy} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-xs font-bold text-white"><Network size={15}/>{busy === "topology" ? "Discovering..." : "Discover topology"}</button></div></Card><Card className="p-6"><div className="grid gap-4 sm:grid-cols-3"><Metric label="Registered devices" value={k.devices ?? "—"}/><Metric label="Down devices" value={k.downDevices ?? "—"} tone="red"/><Metric label="Correlation engine" value="READY" tone="green"/></div></Card></div>}
            {tab === "correlation" && <div className="space-y-5"><Card className="p-6"><div className="flex items-center justify-between"><div><Badge tone="red">4.2 Critical</Badge><h3 className="mt-3 text-xl font-semibold text-white">Incident correlation & suppression</h3><p className="mt-2 text-sm text-slate-500">Group downstream symptoms around the most likely upstream fault and expose suppressed child incidents.</p></div><button onClick={() => run("correlation", async () => setCorrelation(await request("/api/incidents/correlation/rebuild", { method: "POST" })))} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-xs font-bold text-white"><GitBranch size={15}/> Rebuild</button></div></Card>{correlation && <div className="grid gap-4 sm:grid-cols-3"><Metric label="Active incidents" value={correlation.activeIncidents}/><Metric label="Correlated groups" value={correlation.correlatedGroups}/><Metric label="Suppressed children" value={correlation.suppressedChildren} tone="amber"/></div>}{correlation?.groups?.map(g => <Card key={g.correlationGroupId} className="p-5"><div className="flex flex-wrap items-center gap-2"><Badge tone="red">ROOT</Badge><span className="font-mono text-sm text-white">{g.rootIncidentId}</span><span className="text-xs text-slate-500">{g.rootDevice}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{g.children.map(c => <div key={c.incidentId} className="rounded-xl border border-slate-800 bg-slate-950/60 p-3 text-xs"><div className="flex justify-between"><span className="font-mono text-slate-300">{c.incidentId}</span><Badge tone="amber">{c.confidence}%</Badge></div><p className="mt-2 text-slate-500">{c.device}</p></div>)}</div></Card>)}</div>}
            {tab === "rca" && <div className="space-y-4"><div><Badge tone="red">4.3 Critical</Badge><h3 className="mt-3 text-xl font-semibold text-white">Root-cause analysis</h3></div>{(rca?.analyses || []).map(a => <Card key={a.incidentId} className="p-5"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-sm text-white">{a.incidentId}</span><Badge tone={a.confidence >= 80 ? "green" : "amber"}>{a.confidence}% confidence</Badge></div><h4 className="mt-3 font-semibold text-blue-200">{a.cause}</h4><p className="mt-2 text-xs text-slate-500">{a.nextAction}</p><div className="mt-3 flex flex-wrap gap-2">{a.evidence.map(e => <span key={e} className="rounded-lg bg-slate-950 px-2 py-1 text-[10px] text-slate-500">{e}</span>)}</div></Card>)}{!rca?.analyses?.length && <Card className="p-10 text-center text-sm text-slate-500">No RCA candidates loaded. Refresh this tab.</Card>}</div>}
            {tab === "health" && <div className="space-y-5"><div><Badge tone="amber">4.5 High</Badge><h3 className="mt-3 text-xl font-semibold text-white">Advanced interface health</h3><p className="mt-2 text-sm text-slate-500">Live utilization, errors, discards and historical telemetry are already collected by the interface health engine.</p></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Average utilization" value={`${Number(k.avgUtilization || 0).toFixed(1)}%`}/><Metric label="Peak utilization" value={`${Number(k.peakUtilization || 0).toFixed(1)}%`} tone={k.peakUtilization >= 85 ? "amber" : "green"}/><Metric label="Errors + discards" value={k.interfaceErrors ?? "—"} tone={k.interfaceErrors ? "red" : "green"}/></div><Card className="p-5"><p className="text-sm text-slate-400">Use the main <span className="font-semibold text-blue-300">Interface Health</span> workspace for per-device/interface drill-down, historical samples and troubleshooting signals.</p></Card></div>}
            {tab === "analytics" && <div className="space-y-5"><div><Badge tone="amber">4.6 High</Badge><h3 className="mt-3 text-xl font-semibold text-white">Historical analytics</h3></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Incidents" value={analytics?.summary?.incidentCount ?? "—"}/><Metric label="Samples" value={analytics?.summary?.sampleCount ?? "—"}/><Metric label="Avg utilization" value={`${Number(analytics?.summary?.averageUtilization || 0).toFixed(1)}%`}/></div><Card className="p-5"><div className="flex h-52 items-end gap-1">{(analytics?.timeline || []).map(point => <div key={point.time} title={`${point.time}: ${point.incidents} incidents`} className="flex-1 rounded-t bg-blue-500/50 hover:bg-blue-400" style={{height:`${Math.max(4, Math.min(100, point.incidents * 18))}%`}}/>)}{!analytics?.timeline?.length && <p className="m-auto text-sm text-slate-600">No incident samples in this window.</p>}</div></Card></div>}
            {tab === "changes" && <div className="space-y-5"><div className="flex items-end justify-between"><div><Badge tone="amber">4.8 Medium</Badge><h3 className="mt-3 text-xl font-semibold text-white">Configuration change detection</h3><p className="mt-2 text-sm text-slate-500">Capture device inventory/configuration fingerprints and compare successive snapshots.</p></div><button onClick={() => run("changes", async () => setChanges(await request("/api/phase4/config-changes")))} className="rounded-xl border border-slate-700 px-4 py-3 text-xs font-bold text-slate-200">Refresh changes</button></div><Card>{(changes?.changes || []).map(c => <div key={`${c.deviceId}-${c.capturedAt}`} className="border-b border-slate-800/70 p-4 last:border-0"><div className="flex flex-wrap justify-between gap-2"><span className="font-semibold text-white">{c.hostname}</span><Badge tone="amber">CHANGED</Badge></div><p className="mt-2 text-xs text-slate-500">{c.changes.join(" · ")}</p></div>)}{!changes?.changes?.length && <div className="p-10 text-center text-sm text-slate-600">No configuration changes detected yet.</div>}</Card></div>}
            {tab === "automation" && <div className="space-y-5"><div><Badge tone="amber">4.9 Medium</Badge><h3 className="mt-3 text-xl font-semibold text-white">Network automation</h3><p className="mt-2 text-sm text-slate-500">Pre-approved operational workflows with visible results. No unattended device configuration writes.</p></div><div className="grid gap-3 sm:grid-cols-2"><button onClick={() => run("auto-correlation", () => automation("correlate"))} className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 text-left hover:border-blue-500/30"><GitBranch className="text-blue-300"/><p className="mt-4 font-semibold text-white">Re-correlate incidents</p><p className="mt-1 text-xs text-slate-600">Rebuild symptom/root relationships.</p></button><button onClick={() => run("auto-topology", () => automation("topology"))} className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 text-left hover:border-blue-500/30"><Network className="text-blue-300"/><p className="mt-4 font-semibold text-white">Discover topology</p><p className="mt-1 text-xs text-slate-600">Run CDP/LLDP discovery on demand.</p></button></div></div>}
            {tab === "assistant" && <div className="space-y-5"><div><Badge tone="green">4.10 Later</Badge><h3 className="mt-3 text-xl font-semibold text-white">AI troubleshooting assistant</h3><p className="mt-2 text-sm text-slate-500">Evidence-first troubleshooting guidance. The current implementation is deterministic/rule-assisted and does not invent telemetry.</p></div><Card className="p-5"><div className="flex gap-2"><div className="flex-1"><input value={question} onChange={e => setQuestion(e.target.value)} onKeyDown={e => e.key === "Enter" && ask()} className="form-input" placeholder="Ask about the current network state..."/></div><button onClick={ask} disabled={busy === "assistant"} className="rounded-xl bg-blue-600 px-4 text-xs font-bold text-white"><Search size={15}/></button></div>{assistant && <div className="mt-5 rounded-2xl border border-blue-500/15 bg-blue-500/5 p-5"><div className="flex items-center gap-2 text-xs font-semibold text-blue-300"><Bot size={15}/> Evidence-based response</div><p className="mt-3 text-sm leading-6 text-slate-300">{assistant.answer}</p><div className="mt-4 grid gap-2 sm:grid-cols-4">{Object.entries(assistant.evidence || {}).map(([key, value]) => <div key={key} className="rounded-lg bg-slate-950/70 p-2 text-center"><p className="text-[9px] uppercase text-slate-600">{key}</p><p className="mt-1 text-sm font-bold text-white">{value}</p></div>)}</div></div>}</Card></div>}
          </main>
        </div>
      </div>
    </div>}
  </>;
}
